// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrTjWKirEmrXGFd6JRz-KamlDF6eWuKQw',
    appId: '1:103015596170:web:fa55539d5102fe7df32d73',
    messagingSenderId: '103015596170',
    projectId: 'trailguide-4172e',
    authDomain: 'trailguide-4172e.firebaseapp.com',
    storageBucket: 'trailguide-4172e.firebasestorage.app',
    measurementId: 'G-PZ0W430MW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlOGTyah0Di9PlZHnhwFvMtkKum-0CBBg',
    appId: '1:103015596170:android:ebf0c18088c38f26f32d73',
    messagingSenderId: '103015596170',
    projectId: 'trailguide-4172e',
    storageBucket: 'trailguide-4172e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRaco6_dR79zSunKR24Fg4IRvrwmK1uqo',
    appId: '1:103015596170:ios:66cd7d668eb24082f32d73',
    messagingSenderId: '103015596170',
    projectId: 'trailguide-4172e',
    storageBucket: 'trailguide-4172e.firebasestorage.app',
    iosBundleId: 'com.example.trailguide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRaco6_dR79zSunKR24Fg4IRvrwmK1uqo',
    appId: '1:103015596170:ios:66cd7d668eb24082f32d73',
    messagingSenderId: '103015596170',
    projectId: 'trailguide-4172e',
    storageBucket: 'trailguide-4172e.firebasestorage.app',
    iosBundleId: 'com.example.trailguide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrTjWKirEmrXGFd6JRz-KamlDF6eWuKQw',
    appId: '1:103015596170:web:f21edc9a62e81e17f32d73',
    messagingSenderId: '103015596170',
    projectId: 'trailguide-4172e',
    authDomain: 'trailguide-4172e.firebaseapp.com',
    storageBucket: 'trailguide-4172e.firebasestorage.app',
    measurementId: 'G-MNJ3V85286',
  );
}
